# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('request_category', models.CharField(max_length=100)),
                ('request_datetime', models.CharField(max_length=50)),
                ('request_name', models.CharField(max_length=100)),
                ('request_ownername', models.CharField(max_length=100)),
            ],
        ),
    ]
