# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_automation', '0002_requestdetails_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetails',
            name='request_datetime',
            field=models.CharField(max_length=100),
        ),
    ]
